### ISSUE TITLE
7Span: Home Page Bugs: 08/25/23

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#108]
- [x] On each of the landing page images, please move the 'Learn More' underneath the first paragraph instead of under the photo caption. 

<img width="1422" alt="Screen Shot 2023-08-25 at 6 06 57 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/7ff246ff-f91e-4584-9d98-0bc24dc232fb">

- [x] Please change the logo on the footer of the homepage to white text, black and red icon, see image below

https://www.dropbox.com/scl/fi/m0pnalfhstz8qgdwq5sn6/PEMM-Logo-white-text-black-logo.png?rlkey=xsxasph2zt5mkv212wgxqey7e&dl=0

**Comment by WendyLBelcher** [comment]
- [ ] the logo is not aligned vertically over the tag line. 
![logo not align](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/dc75f8dc-8267-4ea8-9770-d6d052344705)

**Comment by WendyLBelcher** [comment]
- [ ] Make navigation bar buttons orange when on page
When on the Story Index page, "Stories" in Navigation Bar should be orange, etc.
![nav bar home](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/be3c6417-cb95-4796-a5e2-5835eb1fb0d1)
