### ISSUE TITLE
7Span: Home Page: Social Media change request 9/24/23

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#143]
- [x] Add our social media handles using their icons
Twitter
Facebook
Instagram
Tiktok

Not sure about placement. Perhaps like this? (Do NOT include white background)
![footer social media4](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/9698246e-cefd-4d92-a026-c96316900b85)

- [x] Bring up email address (a little bit) and copyright line (see arrows), so bottom of footer is more aligned

**Comment by blainealem** [comment]
Instagram links: 
FB: [www.facebook.com/pemmaryam](facebook.com/pemmaryam)
IG:

**Comment by WendyLBelcher** [comment]
### Social Media links
- [ ] Make link to a new tab
Note: Clicking on social media should not take the user out of the page, but take users to a new tab
