### ISSUE TITLE
7Span: Manuscript Index page: Reopened: Bug fixed in September is now wrong again 11/3/23

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#156]
### Filter
- [x] Fix filter `With unique stories`
Lots of manuscripts have unique stories. This result is impossible.
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/c06d5074-fe1c-4ce2-8975-79cc53f9324f)

**Comment by WendyLBelcher** [comment]
### Filter change request
- [ ] Add reset button on Filter (same as change request for Story Detail page)

**Comment by WendyLBelcher** [comment]
### Locations (sidebar)
- [ ] Fix Manuscript's Known Region of Origin 

If selected, it retrieves 0 results for Turkey and Syria. That's impossible.

### Filter change request
- [ ] Add reset button on Filter (same as change request for Story Detail page)

**Comment by WendyLBelcher** [comment]
### Filter (sidebar) (change request not a bug)
- [ ] Add reset button on Filter (same as change request for Story Detail page)

**Comment by WendyLBelcher** [comment]
### Manuscript Table Field Date Manuscript Created
- [ ] Fix  date when manuscript_date_range_start and manuscript_date_range_end are the same

PEMM Issues ticket 110 said: 
If `manuscript_date_range_start `and `manuscript_date_range_end` are the same, remove the hyphen and only use one date.
![1400 once](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/26bf7a69-7f8c-4cf7-9c28-78c58847ccb6)

**Comment by WendyLBelcher** [comment]
### Manuscript Table Field Manuscript's Number of Unique Stories
- [ ] Fix Manuscript's Number of Unique Stories
EMML 6835 has our highest number of unique manuscripts. Here it shows as having zero. That is wrong. 
![dabra](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/a0ec3981-8150-405c-ad68-31b1233a267e)

PEMM Issues ticket 110 said:
Use story_instance table to identify all the stories for a manuscript. Once those stories are identified, use canoncial_story table to identify how many of those stories have field total_records = 1. Count all stories in that manuscripts with total_records = 1.

Clearer instructions are:
- [ ] Use `Story Instance` table to identify all the stories for one manuscript. 
- [ ] Check those stories against `Canonical Story` table for unique `canonical_story_id` with `total_records` field  = 1
- [ ] Display total number of unique `canonical_story_id` with `total_records` field  = 1

**Comment by WendyLBelcher** [comment]
Ignore this comment
### Manuscript's Place of Origin
PEMM had too many long strings in this field ms_location_note. I shortened all the Magdala ones and put what was there into the Manuscript_note field

**Comment by blainealem** [comment]
### Issue with Scroll Up on Sliders

- [ ] As discussed during our 9/25 meeting, please change "Number" to "No." all all three sliders (Number of Stories, Paintings, Unique Stories)
- [ ] As discussed during our 9/25 meeting, please change the speed of the slider function to at least 5 seconds that way user has enough time to make a selection before the screen scrolls up

**Comment by WendyLBelcher** [comment]
- [x] Fix `Manuscript's Date of Creation` slider
Nothing over 1397 should be showing, but many are, including this one from the 1400s
![slider date](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/e2a61b25-9a7f-4109-b51a-1d7e7f07f7b2)

**Comment by WendyLBelcher** [comment]
### Filter (sidebar)
- [x] Fix multiple buttons (almost none are working properly) (see below for programming instructions first)
![buttons don't work](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/a3f32674-190d-47a4-8ccf-6d470b785eff)

Button 1 (see screenshot above):
"With paintings" button is selected, but manuscripts with 0 for `Manuscript's Number of Paintings` are showing. That is impossible.

Button 2 (see screenshot above):
"With online digital copy" button is selected, but manuscripts with nothing under `Link to Manuscript Online` are showing. That is impossible.

Button 4 (see screenshot above):
"With unique stories" button is returning only a few results, only those with 1 or 2 unique stories. But we have one manuscript with 60+ unique stories.

Button 5 (see screenshot above):
"Oldest manuscripts" button is selected but manuscripts with "1800-1899" for `Date Manuscript Created` are showing. That is wrong.

Button 3 (see screenshot below):
"With color digital copy" button is selected but no results. That is wrong. We have hundreds in color.
![with color](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/8cdcf2e1-2617-47da-9515-4bd2aa59e4f9)


Button 6 (see screenshot below):
"Recent manuscripts" button is selected, but manuscripts with "1508-1540" for `Date Manuscript Created` are showing. 
![recent wrong](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/9428a188-fc6a-4be7-babf-e5ba6138f621)
