### ISSUE TITLE
7 Span: Stories Index, Manuscript Index, Paintings Index pages: Results

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#224]
### Manuscript Index Results
- [x] Shorten filter search bar, keep left
- [x] Change wording from "Filter" to "Search manuscript names"
- [x] Move Results field to the center (approximately)
- [x] Keep Title View where it is, to the far right

Change from
![manuscript index results](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/a4c9ba85-cae5-4f76-805e-6afaf1231ff0)

to something like this:
![aaasearch filter2](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/73c0d77b-f3ad-43e9-a0ec-7e353e56de9f)

**Comment by WendyLBelcher** [comment]
### Manuscript Index Results
- [ ] Shorten filter search bar, keep left
- [ ] Change wording from "Filter" to "Search manuscript names"
- [ ] Move Results field to the center (approximately)
- [ ] Keep Title View where it is, to the far right

Something like this
![aaasearch filter](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/e426c505-3370-436a-9fb3-ba028d017cb3)

Something like this:
![aaaa results2](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/220522f6-d6e0-49f3-ae16-a266f275cfd8)It should look something like this on the Manuscript Index page

![manuscript index results](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/a4c9ba85-cae5-4f76-805e-6afaf1231ff0)

**Comment by WendyLBelcher** [comment]
### Paintings Index page Results
- [ ]  Add gray wording in search box "Search painting descriptions"
- [ ]  Place Results button somewhere

**Comment by WendyLBelcher** [comment]
### Paintings Index page Results
My Mistake.  Change wording to match other index pages
- [ ] Change gray wording in search box "Search painting descriptions" to the green lettering across the top of the filter as in story index page
Like this:
![dog search](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/58eb886a-58ef-4b0b-9ada-8d0c3607edb0)
