### ISSUE TITLE
7Span: 2. Story Index page: Print Only Directus field 10/24/23

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#370]
v

**Comment by WendyLBelcher** [comment]
### Filter in top part
- [ ] Create Radio Button
`Print Only`
`Exclude Print Only`



Programming: 
If, for each `Story Instance` table `canonical story id`, the id has manuscripts that ALL include "TGS" and no manuscripts that do NOT include TGS
Display 
[ ] Print Only
Then, exclude the above programming
Display
[ ] Exclude Print Only`

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/f8b6adb4-a856-4122-8dec-f03cf87bd9c3)
Note: Some stories have never appeared in a manuscript, only in the TGS volumes. Many stories appear in a manuscript and in print

**Comment by WendyLBelcher** [comment]
- [ ] Add new filter button (not a radio button)
Wording
Popular Stories
Programming:
If story appears in `story instance` table in manuscript `TG (EOTC) 1924-1931`

**Comment by WendyLBelcher** [comment]
### Wording changes
- [ ] Change this filter wording
With Hymn
to 
With Hymns

- [ ] Correct typo
Comman Stories
to
Common Stories

**Comment by WendyLBelcher** [comment]
- [ ] Correct programming on Print Only and Exclude Print Only
The filter is Print Only, but every ID showing is NOT Print Only
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/21f3576a-f953-4af1-b7f0-27eb27da6066)

Note: Some stories appear only in print books, never in a parchment manuscript. Those are Print Only. We know they are Print Only if the story id has ONLY in `manuscript `table `manuscript_name `with the abbreviation TGS. If the story ID has even one manuscript marked BOr or EMML or EMDL or PEM or GEM etc. etc. etc., it is NOT print only.

**Comment by blainealem** [comment]
As of 10/26 we are performing the following steps for the "Print Only" and "Exclude Print Only" radio button: 

- [ ] First, in Directus, create a field in the `canonical story` table called "Print Only". This will be a boolean field. 

- [ ] Program the field in Directus to be automatic with the following calculation: 

- Loop through the `Story Instance` table and identify all story instances with `manuscript_name` containing TGS. (Group A)
- Loop through the `Story Instance` table and identify all story instances with `manuscript_name` NOT containing TGS. (Group B)
- Compare Group A and Group B. Identify whether `canonical_story_ID` for story instances in Group A appear in Group B (vlookup). 
- If there are `canonical_story_ID` that appear in both Group A and Group B, the new "Print Only" field in Directus is False (unchecked)
- For any `canonical_story_ID` that appears ONLY in Group A, the new "Print Only" field in Directus is True (checked)

**Comment by blainealem** [comment]
As of 10/26 we are performing the following steps for the "Print Only" and "Exclude Print Only" radio button: 

- [ ] First, in Directus, create a field in the `canonical story` table called "Print Only". This will be a boolean field. 

- [ ] Program the field in Directus to be automatic with the following calculation: 

- Loop through the `Story Instance` table and identify all story instances with `manuscript_name` containing TGS. (Group A)
- Loop through the `Story Instance` table and identify all story instances with `manuscript_name` NOT containing TGS. (Group B)
- Compare Group A and Group B. Identify whether `canonical_story_ID` for story instances in Group A appear in Group B (vlookup). 
- If there are `canonical_story_ID` that appear in both Group A and Group B, the new "Print Only" field in Directus is False (unchecked)
- For any `canonical_story_ID` that appears ONLY in Group A, the new "Print Only" field in Directus is True (checked)

**Comment by WendyLBelcher** [comment]
### Programming (see same programming for Manuscript Index page, ticket 371)
If, for each canonical story id, `Story instance` field `stanza `is Yes , include in filter
[ ] With Hymn
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d5b02eae-8d01-44af-bad3-6b200370da82)

**Comment by WendyLBelcher** [comment]
One more addition to the programming.

- [ ] If `canonical story` table `type_of_story` is Miracle of Mary, include in Print Only
- [ ] If `canonical story` table `type_of_story` is Life of Mary, include in Exclude Print Only

Current results
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/230b0882-e25f-45c4-b29f-cc1a5cadf184)

Future results
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/2daaef68-c99a-4a0a-8447-5597f5ea9f51)
