### ISSUE TITLE
7Span: Paintings Index Page: Digital Quality Bug remaining

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#394]
- [x] Correct Digital Quality 

- [x] Correct "Exclude Image Not Available" dropdown to exclude `image_link` and `non_iiif_image_link` are both NULL
**Bug:** The "Exclude Image Not Available" filter under Digital Quality is not working (see ref image below). 

**Fix:** Selecting "Exclude Image Not Available" should filter out all images in which the `Paintings` table, field `image_link` and `non_iiif_image_link` are both blank. When this filter is selected, no images that have the text "This painting is described and is keyworded in PEMM, but is not available for viewing through PEMM" should appear. 

<img width="1176" alt="Screen Shot 2023-10-11 at 6 40 56 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/33ed9b8c-2c31-46a9-9b35-abb502ee7d3f">

- [x] Correct drop downs Exclude Color Paintings and Exclude Black and White to display  `image_link` and `non_iiif_image_link` are both NULL

**Comment by WendyLBelcher** [comment]
Some are now working correctly. 
- [ ] This combination is correct.

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/6a56726f-9118-4ffe-a378-b40b27e47b83)

- [ ] This combination is correct
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/efc8f51a-d34e-42ad-9736-44b023f84066)

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/59271268-d37d-4e2a-9bdf-250e8f3054c8)

But some are not working correctly. 
- [ ] This combination is NOT correct.
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d6b77131-9faf-4cef-8ec1-58c8a516dc94)
We have hundreds and hundreds and HUNDREDS of Images not Available. 0 results is wrong

- [ ] Correct Exclude Color Paintings
- [ ]

**Comment by WendyLBelcher** [comment]
### Exclude Color Paintings
Exclude Manuscript table scans_color = Yes, AND If paintings table link is NOT NULL

### Exclude Image not Available
Exclude [no check of manuscript table,] only if paintings table links are NULL

### Exclude Black and White
Exclude manuscript table scans_color = No, AND if paintings table links are NOT NULL
