### ISSUE TITLE
7Span: Paintings 2: Paintings Detail Page

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#4]
### Purpose
The Paintings Detail Page allows users to see all the information about each painting in the database. 

### Access
Accessed by clicking on any painting (whether in `Painting Index `page,  `Paintings by Story Detail` page, or `Paintings by Manuscript detail` page, and in carousel on `Story Detail `page.

### Web Address Links
The web address for all painting detail pages is /painting/ + `Manuscript `table `web_page_address` _ `painting_unique_id`
For example, if `Manuscript `table `web_page_address` = BerOrOct1270 and `painting_unique_id` = 838, the web address is:
/painting/BerOrOct1270_38

### Design
Note: image below is for general guidance; some wording is different
![8A Painting detail page revised_Page_1](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/006f8366-0aa6-46c0-bcb9-991c403686d3)

**Comment by WendyLBelcher** [comment]
### Programming of Image (left)
- [ ] Create the painting detail page for each `painting_unique_id`
- [ ] Create zoom buttons (if possible) and expand to whole screen (as shown in design above
- [ ] Display painting on the left using `Painting` table `image_link `(or, if empty, `non_iiif_image_link`)

### Programming of Wording (right)
- [ ] Display `Canonical Story` table `PEMM_Short_Title`??? field across top (in green, head size)

- [ ] Program words "Painting's Number of Episodes:"
- [ ] Display all `Painting` table `number_of_episodes`


- [ ] Program words "PEMM Painting Episode Captions:"
- [ ] Display `Painting` table `episode_description` (`episode_location_on_page`) 
Note: This is for each `painting_unique_id`, each `episode_description` on a separate line, ordered by `episode_number`. Parentheses around `episode_location_on_page`


- [ ] Program words "Painting's Gəˁəz Caption in Translation:"
- [ ] Display `Painting` table `episode_caption`

- [ ] Program words "Objects in Painting:"
- [ ] Display  `Painting` table `episode_keywords_objects`


- [ ] Program words "Agents in Painting:"
- [ ] Display `Painting` table `episode_keywords_agents`


- [ ] Program words "Manuscript:"
- [ ] Display `Painting` table `manuscript`, f. `painting_folio`, s. `painting_scan`
- [ ] Place link on `Painting` table `manuscript` of `manuscript_link` 
- [ ] Program words "Date:"
- [ ] Display `manuscript` table `date_range_start` - `date_range_end`

- [ ] Program words "PEMM Painting Id:"
- [ ] Display  `Painting` table `painting_unique_id`


- [ ] Program words "PEMM Story Id:"
- [ ] Display `Painting` table `Canonical_Story_ID`
- [ ] Place link on `Painting` table `Canonical_Story_ID` of relevant PEMM web page


- [ ] Program words "PEMM Manuscripts with paintings of this story:"
- [ ] Display `Painting` table `total_manuscripts_with_this_story_illustrated`
- [ ] Program words "Total paintings of this story:"
- [ ] Display `Painting` table `total_story_id_paintings`

### Programming Buttons
Program orange buttons for "Next Painting," "Previous Painting" for painting detail pages
Use `Painting` table `painting_number` and `canonical_story_id` and `manuscript` to program
If the `Painting` table for (1) any one `canonical_story_id` in (2) any one `manuscript` has (3) a `painting_number` of 2 or higher, do some programing to create a link on the buttons. 
- [ ] Use the lower `painting_number` to link to the previous painting detail page on the word "Previous" and use the higher `painting_number` to link to the next painting detail page on the word  "Next" 
- For example, if  `canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` is 3, link to page for `canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` = 2 on "Previous" and 
`canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` = 4 on "Next"

**Comment by WendyLBelcher** [comment]
### Programming of Wording (right)
- [ ] Display `Canonical Story` table `PEMM_Short_Title`??? field across top (in green, head size)

- [ ] Program words "Painting's Number of Episodes:"
- [ ] Display all `Painting` table `number_of_episodes`


- [ ] Program words "PEMM Painting Episode Captions:"
- [ ] Display `Painting` table `episode_description` (`episode_location_on_page`) 
Note: This is for each `painting_unique_id`, each `episode_description` on a separate line, ordered by `episode_number`. Parentheses around `episode_location_on_page`


- [ ] Program words "Painting's Gəˁəz Caption in Translation:"
- [ ] Display `Painting` table `episode_caption`

- [ ] Program words "Objects in Painting:"
- [ ] Display  `Painting` table `episode_keywords_objects`


- [ ] Program words "Agents in Painting:"
- [ ] Display `Painting` table `episode_keywords_agents`


- [ ] Program words "Manuscript:"
- [ ] Display `Painting` table `manuscript`, f. `painting_folio`, s. `painting_scan`
- [ ] Place link on `Painting` table `manuscript` of `manuscript_link` 
- [ ] Program words "Date:"
- [ ] Display `manuscript` table `date_range_start` - `date_range_end`

- [ ] Program words "PEMM Painting Id:"
- [ ] Display  `Painting` table `painting_unique_id`


- [ ] Program words "PEMM Story Id:"
- [ ] Display `Painting` table `Canonical_Story_ID`
- [ ] Place link on `Painting` table `Canonical_Story_ID` of relevant PEMM web page


- [ ] Program words "PEMM Manuscripts with paintings of this story:"
- [ ] Display `Painting` table `total_manuscripts_with_this_story_illustrated`
- [ ] Program words "Total paintings of this story:"
- [ ] Display `Painting` table `total_story_id_paintings`

### Programming Buttons
Program orange buttons for "Next Painting," "Previous Painting" for painting detail pages
Use `Painting` table `painting_number` and `canonical_story_id` and `manuscript` to program
If the `Painting` table for (1) any one `canonical_story_id` in (2) any one `manuscript` has (3) a `painting_number` of 2 or higher, do some programing to create a link on the buttons. 
- [ ] Use the lower `painting_number` to link to the previous painting detail page on the word "Previous" and use the higher `painting_number` to link to the next painting detail page on the word  "Next" 
- For example, if  `canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` is 3, link to page for `canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` = 2 on "Previous" and 
`canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` = 4 on "Next"

**Comment by WendyLBelcher** [comment]
### Programming Buttons
Program orange buttons for "Next Painting," "Previous Painting" for painting detail pages
Use `Painting` table `painting_number` and `canonical_story_id` and `manuscript` to program
If the `Painting` table for (1) any one `canonical_story_id` in (2) any one `manuscript` has (3) a `painting_number` of 2 or higher, do some programing to create a link on the buttons. 
- [ ] Use the lower `painting_number` to link to the previous painting detail page on the word "Previous" and use the higher `painting_number` to link to the next painting detail page on the word  "Next" 
- For example, if  `canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` is 3, link to page for `canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` = 2 on "Previous" and 
`canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` = 4 on "Next"

![next previous button](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/855ef66c-e582-462b-a0fd-52cfb88ec8ef)

**Comment by WendyLBelcher** [comment]
IGNORE ALL of the FOLLOWING
### Programming Buttons
Program orange buttons for "Next Painting," "Previous Painting" for painting detail pages
Use `Painting` table `painting_number` and `canonical_story_id` and `manuscript` to program
If the `Painting` table for (1) any one `canonical_story_id` in (2) any one `manuscript` has (3) a `painting_number` of 2 or higher, do some programing to create a link on the buttons. 

- [ ] Use the lower `painting_number` to link to the previous painting detail page on the word "Previous" and use the higher `painting_number` to link to the next painting detail page on the word  "Next" 
- For example, if  `canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` is 3, link to page for `canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` = 2 on "Previous" and 
`canonical_story_id` = 4 and `manuscript` = BOr 349 and `painting_number` = 4 on "Next"

If  a `canonical_story_id` and  `manuscript` has only  `painting_number` = 1 and no 2, etc. buttons will have no effect. 
[Not sure of the solution for this?]

![next previous button](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/855ef66c-e582-462b-a0fd-52cfb88ec8ef)
