### ISSUE TITLE
7Span: UX changes: filter radio buttons: make relationship clear (high priority)

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#450]
## User Experience changes
Clarify which radio buttons are pairs

**Comment by blainealem** [comment]
**2) Filtered Search on Manuscript & Story Index Pages**

- [ ] Check boxes are used when multiple items can be selected, and radio buttons are used when the user needs to make a choice. Thus, we need to group items that are checkbox type together and seperaate items where the users only has one choice. See example below: 

<img width="225" alt="image" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/bc2c3732-15ae-4db1-86fd-43c72197e3d6">

**Comment by blainealem** [comment]
**3) Filtered Search Scrolls to the Top (Bug)**

On both the story index and manuscript index pages we are still experiencing the UI scroll to the top after making a selection in the location or region filter. Please remove this auto scroll feature 

<img width="263" alt="image" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/0adbfa7b-22c2-46bb-9e17-a9072fd6c6cf">

**Comment by blainealem** [comment]
4) Change Design of Story Origin (CR)

- [ ] Change the design of the story origin so it is clear which countries are contained in the continent. Example below: 
<img width="260" alt="Screen Shot 2023-10-31 at 4 53 45 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/2d90545f-eb7e-4170-9ed2-ea8a0ba48bd8">

**Comment by blainealem** [comment]
**5) Paintings Index Page**

- [ ] Remove the additional navigation bar of the paintings index page. See ref image below: 
<img width="878" alt="image" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/44b44495-62ef-49c9-9a08-675e3c603f3e">

**Comment by blainealem** [comment]
6) `To Cite this Translation` on Story Detail Page 

- [ ]  Remove active link from `To Cite this Translation` on Story Detail Page 
<img width="451" alt="Screen Shot 2023-10-31 at 5 05 39 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/6787c721-4393-427c-8f0b-cab89b82b4b7">

**Comment by WendyLBelcher** [comment]
**6) `To Cite this Translation` on Story Detail Page** 

- [ ]  Remove active link from `To Cite this Translation` on Story Detail Page 
<img width="451" alt="Screen Shot 2023-10-31 at 5 05 39 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/6787c721-4393-427c-8f0b-cab89b82b4b7">

**Comment by WendyLBelcher** [comment]
### Links
- [ ] On hover make links obvious
Note: Links do not look like links. We do not want to do underscore. Is there a different way to make links obvious?

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/6df8a4e5-6707-40e3-aff2-a08293ebfc65)

**Comment by WendyLBelcher** [comment]
### Ignore for now
Paintings Index page
Add filter on manuscript pages?
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/a2b9e75b-a87c-45f1-8c42-d3d932d50e1a)

**Comment by WendyLBelcher** [comment]
Manuscript Index page
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/8ba1f100-919f-48e2-9514-1f31ad300c07) 
- [ ] Add colon in the following words:
Africa:
Middle East:
North America:
Europe:

- [ ]  Change so only one button can be selected or light up at a time
Note: If you click on any two (Egypt and Ethiopia), you get zero results. Or the results don't change (Africa and Egypt has the same result as just Egypt). There is no point in being able to click more than one at a time.
Note: So, after the change, if one story origin button is clicked, and you click on another one, the first one should go off.

**Comment by WendyLBelcher** [comment]
### Ignore for now
Links in prose on the website
On hover make links obvious
Note: in the Index page, links change to orange on hover. Do that throughout?
UX consultant: the Links do not look like links. 
Note: We do not want to do underscore. Is there a different way to make links obvious?

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/6df8a4e5-6707-40e3-aff2-a08293ebfc65)

**Comment by WendyLBelcher** [comment]
Possible alternate color for yellow
Darker, gold
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/bd16265d-dd66-4b2e-90bd-fb49e7fe44ad)

Purple Blue
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/65d8abc7-9af5-4c71-a2f3-7f69e5933c15)

Light blue
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d2ddd924-3320-42c4-a434-616c4ebb7612)

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/f42cf88e-ffdb-4a9a-987a-56c678237e8d)

**Comment by WendyLBelcher** [comment]
### Ignore

Purple Blue (not common in old paintings)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/65d8abc7-9af5-4c71-a2f3-7f69e5933c15)

Light blue (not enough contrast?)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d2ddd924-3320-42c4-a434-616c4ebb7612)

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/f42cf88e-ffdb-4a9a-987a-56c678237e8d)

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/685c1bad-9de0-4437-8dce-9d835d5b527d)

**Comment by WendyLBelcher** [comment]
Make back buttons visible in mobile, not visible in laptop view

**Comment by WendyLBelcher** [comment]
## Ignore this one, do NOT do
Ignore Whole site colors
Change current yellow background and highlighting to this orange? We have not finalized this yet.
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/17b5d5bc-4c35-4e0c-8e37-6ba4d339fdbd)

### Home page colors
- [ ] Change yellow background of Featured Stories, Featured Manuscripts, Featured Paintings to the orange above
- [ ] Change font on the yellow background to make it whiter and brighter, as above
- [ ] ![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/7629cee3-110d-450c-9411-2a557ed0d6f1)


### Navigation bar and index pages
- [ ] Change yellow highlighting on navigation bar and in index pages to the orange above
- [ ] Change links to turn from green to this gold on hover

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/c7edf929-2a7c-44ea-b5ef-3b6987d5cace)
- [ ] Change yellow of slider to match this orange above
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/00703dfe-a772-4bb7-8011-a761d3a70317)

Changing white to orange on green backgroun?
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/3d1f11aa-cbdd-4c39-a1c9-73a2ae7d3860)

**Comment by WendyLBelcher** [comment]
Ignore for now

### Research & Lessons, News & Updates, Events & Workshops
Maybe, I'm not sure?
- [ ] Do not differentiate backgrounds on tiles. All tiles should be green, not green for one type and yellow for another
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/50263bdf-2abe-4362-8b61-492e49c99d9b)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/3a7d379e-d568-4309-addc-efd6c0bc16ee)


- [ ] Change background on buttons to the orange above
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/79fb8f58-436d-4722-b6ba-4b184f89f305)

**Comment by WendyLBelcher** [comment]
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/443e6460-b5b1-442b-972f-0b77532ddad4)
