### ISSUE TITLE
7Span: Paintings 1: Paintings Index Page

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#46]
### Purpose
The Paintings Index Page allows users to see every painting in the database. 
The default display is of paintings in color
- [ ] Default paintings = `Paintings` table `manuscript_link` with a url (htttp) AND `Manuscript` table `scans_of_manuscripts_in_color` = **Yes**

### Access
Accessed by clicking on navigation bar "All Paintings" 

### Design
Display every painting on a tile
- [ ] Order paintings by `Manuscript` table `collection `= BOr (BL) and then = PEM (Princeton). Order randomly after that.

### Web Address Links
The link on all `Painting Index` page tiles is /painting/ + `Manuscript `table `web_page_address` _ `painting_unique_id`
For example, if `Manuscript `table `web_page_address` = BerOrOct1270 and `painting_unique_id` = 838, the web address is
/painting/BerOrOct1270_38

### Programming
Follow programming for filter at https://www.ethiopicmary.com/paintings (but see comment below)
Follow programming for displaying images (but do NOT stretch) at https://www.ethiopicmary.com/paintings
Follow programming for black box underneath at https://www.ethiopicmary.com/paintings
Do NOT follow programming for wording below painting (see comment below)

Original Design (now changed, see below)
<img width="795" alt="Screen Shot 2023-08-17 at 7 11 31 PM" src="https://github.com/PrincetonPEMM/pemm-issues/assets/104459635/d53387f5-fc95-4dbf-8892-bc04391073ff">

New Design (also not quite right)
![ethiopicmary](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/23563611-a5ed-4e5f-8b17-13c5fdc20168)

**Comment by WendyLBelcher** [comment]
### Filter
This is the design of the filter in Ethiopic Mary. It is across the top, not the side. To discuss
![filter](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/5829bcbd-036d-45e2-a630-7cd5b5bab5ce)

`Date of Paintings` head
default is all centuries
dropdown is
- 1200s
- 1300s
- 1400s
- 1500s
- 1600s
- 1700s
- 1800s
- 1900s
- 2000s
[these are NOT exclusive options, you can select more than one]
Design question: A slider might be better?

`Paintings in color only `head
default is paintings in color only
dropdowns are
- Include Black & White
- Include image not available 
[these are 3 exclusive options, you can only select one]

`Story Type` head
default is all story types
dropdowns are
- Miracle of Mary
- Life of Mary 
- [these are 2 exclusive options, you can only select one]

Repository of Painting
default is all collections
dropdowns are in the programming for ethiopicmary
![archives1](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/f6c9113f-3b14-419e-8072-d9e96afad198)
![archives2](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/325ff264-90dd-44f7-b6a1-aa6095c0b99b)

**Comment by WendyLBelcher** [comment]
Wendy's note:
Make the seams better
Making the credit line one point smaller
Omit action arrow
Small zoom
Learn more
Nav bar is a touch too big
Align horizontally nav bar exactly in the middle of the logo
featured comes up slow
not as tall, but same width
where the text will go
action item
align logo, make a shade bigger
glow the period in between pages
margins by pixels
space after head is too much in rsearch tool pages 

search not filter
no line between the same entry, data should be more clearly associated
tighter between data and title
heads larger
no underescore on titles in story index, already highlight to yello
a lot of lines on the page
round corner boxes, or matching the countries
make wording closer to the boxes, by moving the boxes to the right
all move to the right a few pixels
serif for story titles
rounded the next page boxes, pagination

first four columns tighter, and the rest longer
move
Story's Date Of Origin [of on the next line]

title view light up

no bar on botton on manuscripts

arrow on filter should flip, hide filter
highlight in yellow

tigher dropdowns on nav bar

background on non data pages a few shades darker than the parchment, tints on them

orange for links


Our People larger
Put Our Team closer to what is after it

2-heads in a different font

green background for the Our Team part
unclicing doesn't work
![spacing](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/385e9f3b-a75b-47b2-9d68-a8eb7faea326)

**Comment by WendyLBelcher** [comment]
### Order of images
The current impression is that they are all the same. We need to make the first twenty look different from each other. Can we give you painting ids to start with?
