### ISSUE TITLE
7Span: Paintings Index page: dropdown colors (approved 1 hour)

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#492]
- [ ] Standardize dropdowns
Accessibility Principle of dropdowns:
White font on green background, turns gold on hover or click
Black font on yellow background
NEVER have white font on yellow background

### Story index page
The Story index page top filter is correct, no change:
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d5fbb220-f502-4e6d-be3f-41040ebe52e8)

- [x] The Story index page buttons are not correct. On click, keep change to yellow background, but keep black font, do not change to white font
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d9ad78e4-36a5-411b-b3f8-1a838be5b715)

- [x] Story index and Manuscript index page: Radio button wording should turn yellow
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/17671b54-5166-4dbc-9b8d-a96e31c57ce0)

### Manuscript index page
The Manuscript index page top filter is correct, no change:
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/60b4e070-2c06-4ea1-8f51-123f8d793991)

- [ ] The Manuscript index page buttons are not correct. On click, keep change to yellow background, but keep black font, do not change to white font
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/4b4ee514-04ba-43f9-964f-546e61c4b1f9)

### Paintings index page
- [ ] Change white background on Paintings pages to yellow background (keep black font)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/7762bba0-289f-4842-9b32-62fad3c9ae48)

### Ignore the following
This is really a bug, but I will count it as a change request
For discussion:
Painting detail page dropdowns should match the Story Detail page and manuscript detail page filters, which are also white on green
One is gold on green with a box; the other is black on white with a thin yellow checkmark (almost impossible to see)
How to make them more similiar?
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/f1a805bf-333b-44d9-ad44-0ad09603100d)

Same here
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/324b7bb2-dacb-4f56-9872-62cf0bf40468)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/f5bc6b8f-4524-4e62-bfb1-704f4958ab68)

**Comment by WendyLBelcher** [comment]
- [ ] Fix display of Internal link on hover. 

Note: It turns yellow and disappears
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/8ab7d5b3-aca3-4a9a-9c99-fb6270469ecd)

**Comment by blainealem** [comment]
- [ ] Please update the featured links (stories, manuscripts, paintings) to be bolded


<img width="1273" alt="Screen Shot 2023-12-04 at 10 50 02 AM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/97380a27-f054-4ded-ba30-78bd688980f6">
