### ISSUE TITLE
7Span: Credit line on paintings detail page (approved 1 hour) (bug 12/4)

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#547]
- [x] Display credit line on painting detail pages
Wording and programming:
Image displayed with permission of [institution].
Example:
Image displayed with permission of Princeton University Library.

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/6d1e6be7-5ea0-48c5-9d89-c114d05159f3)

**Comment by blainealem** [comment]
<img width="1404" alt="Screen Shot 2023-11-21 at 1 20 52 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/d5798291-1e26-4c5e-a8fe-0d52fa1177b8">

**Comment by WendyLBelcher** [comment]
### Ignore for now:


Create links to individual institution.
https://pemm.princeton.edu/research/repositories

Use same programming as on the rest of the page
Use small font so credit fits in no more than two or three lines below the image

Format: 
"Anonymous Artist, [PEMM_short_title], [manuscript_date_range_start-manuscript_date_range_end], manuscript illumination in [manuscript name, folio start/scan start]. Image displayed with permission of [Institution]."

Example:
"Anonymous Artist, The Thirsty Dog, 1700-1799, manuscript illumination in Princeton University Library, Ethiopic Manuscripts, Manuscript No. 57, f. 152v. Image displayed with permission of Princeton University Library."

Placement of image credit below: 
[in black ink not red ink]

<img width="1404" alt="Screen Shot 2023-11-21 at 1 20 52 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/d5798291-1e26-4c5e-a8fe-0d52fa1177b8">

**Comment by WendyLBelcher** [comment]
### Ignore for now:


Create links to individual institution.
https://pemm.princeton.edu/research/repositories

Use same programming as on the rest of the page
Use small font so credit fits in no more than two or three lines below the image

Format: 
"Anonymous Artist, [PEMM_short_title], [manuscript_date_range_start-manuscript_date_range_end], manuscript illumination in [manuscript name, folio start/scan start]. Image displayed with permission of [Institution]."

Example:
"Anonymous Artist, The Thirsty Dog, 1700-1799, manuscript illumination in Princeton University Library, Ethiopic Manuscripts, Manuscript No. 57, f. 152v. Image displayed with permission of Princeton University Library."

Placement of image credit below: 
[in black ink not red ink]

<img width="1404" alt="Screen Shot 2023-11-21 at 1 20 52 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/d5798291-1e26-4c5e-a8fe-0d52fa1177b8">
