### ISSUE TITLE
7Span: Story Detail Page Autogenerated Text Section (3 hours approved)

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#598]
# Bugs
- [ ] Follow the instructions about 50% or higher, below is wrong
This story is extremely common: it appears in 307 out of 677 PEMM manuscripts (46%). It is in the top 15 most common stories.
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/626c0b9b-394f-4d21-a30c-4e86bf31ba95)

# Instructions as of 12/12
### 1 Extremely popular
- [ ] Change wording of this sentence
Old wording: This story is extremely popular: appearing in [xx]% of PEMM manuscripts with five stories or more.
New wording: This story is extremely common: it appears in [xx] out of [yy] PEMM manuscripts (zz%). It is in the top 15 most common stories. 
Example: This story is extremely common: it appears in 473 out of 674 PEMM manuscripts (70.18%). It is in the top 15 most common stories. 

**Programming**
Display this Extremely Common sentence If the [zz] percentage displayed is 50% or more
[xx] = the number of times a `canonical story ID` appears in the `story instance` table. 
**HOWEVER,** any `canonical story ID` that appears MORE THAN ONCE in the SAME manuscript should only be counted ONCE. 
For example `canonical story ID` 163 appears in BAdd (BL) 16192 twice, however this should only be counted once. The total count for ID 163 is 425.

[yy] = total number of manuscripts with `ms status` = complete in the `manuscripts` table. (currently 674)

[zz] = xx/yy percent (for ID 163, this would be 425/674 =  63.05%)

### 2 Very Popular
- [ ] Remove this sentence and condition:
Wording: This story is very popular: appearing in [xx]% of PEMM manuscripts with five stories or more.

### 2 Popular
- [ ] Remove this sentence and condition:
Wording: This story is popular: appearing in [xx]% of PEMM manuscripts with five stories or more.

### 4 Somewhat Popular
- [ ] Remove this sentence and condition:
Wording: This story is somewhat popular: appearing in [xx]% of PEMM manuscripts with five stories or more.

### 4 Rare
- [ ] Change wording of this sentence: 
Old wording: This story is rare: appearing in [xx]% of PEMM manuscripts with five stories or more.
New wording: This story is rare: it appears in [xx] of [yy] PEMM manuscripts. 
Programming:
Display this sentence when [xx] is between 2 and 6 manuscripts
Example: This story is rare: it appears in 2 of 674 PEMM manuscripts.

### 4 Very Rare
- [ ] Remove this sentence and condition:
Wording: This story is very rare: appearing in [xx]% of PEMM manuscripts with five stories or more.

### 5 Uniquely rare
- [ ] Change wording of this sentence: 
Old wording: This story is uniquely rare: appearing in only 1 of the PEMM manuscripts.
New wording: This story is unique: it appears in only 1 of the [yy] PEMM manuscripts.
[yy] = total number of manuscripts with `ms status` = complete in the `manuscripts` table. (currently 674)
Example: This story is unique: it appears in only 1 of the 674 PEMM manuscripts.

### 6 Other
- [ ] For all other cases (most cases) (stories with at least 7 stories AND below 60%) the sentence should be: 
This story appears in [xx] out of [yy] PEMM manuscripts (insert percentage%). 
Example: This story appears in 7 out of 674 PEMM manuscripts (1%). 
Example: This story appears in 50 out of 674 PEMM manuscripts (7.4%)

**Comment by WendyLBelcher** [comment]
IGNORE the following
CR: Update the programming of the sentence in the first paragraph of the story detail page:

The story is **[very popular/popular/rare/very rare]**, appearing in [generated] percent of GMP (among those manuscripts with more than five stories).

Currently, the sentence is programmed using the following logic: 
`Canonical Story` sheet, use `Total Records` column
if more than 300, spell "extremely popular"
if 200 to 299, spell " very popular"
if 50 to 199, spell "popular"
if 10 to 49, spell "somewhat popular"
if 3 to 9, spell "rare"
if 1 or 2, spell "very rare"


- [ ] Count the total number of manuscripts with `ms status` = complete in the `manuscripts` table

**Comment by WendyLBelcher** [comment]
This story is extremely common: it appears in <401x> out of <674> PEMM manuscripts (66%). It is in the top 15 most common stories.
This story is unique. It appears in only one mansucript.

**CR:** Update the programming of this sentence in the first paragraph of the story detail page: 
Old programming:  `canonical story` table field `total records` divided by `481 `
New programming: `canonical story` table field `total records` divided by total number of `manuscripts` table field with `ms status` = `complete` (about 674~)
EXCEPT do not count  `canonical story` table field `canonical_story_ID` TWICE IF it appears twice in one manuscript. 
For example `canonical story ID` 163 appears in BAdd (BL) 16192 twice, however this should only be counted once. The total count for ID 163 is 425. 

Explanation:
The story is [very popular/popular/rare/very rare], **appearing in [generated] percent of GMP** (among those manuscripts with more than five stories).

<img width="1323" alt="Screen Shot 2023-12-01 at 3 52 16 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/bfbfe08f-0d55-4858-a96f-39298dc8638f">

Currently, the percentage is generated by using `canonical story` table, field `total records` as the numerator and static number "481" for the denominator.  We would like to change both these figures:

- [ ] The denominator can no longer be static, it must be dynamic. Update the programming to divide by the total number of manuscripts with `ms status` = complete in the `manuscripts` table. 

- [ ] The numerator = the number of times a single `canonical story ID` appears in the `story instance` table. However, any `canonical story ID` that appears more than once in a single manuscript should only be counted once. For example `canonical story ID` 163 appears in BAdd (BL) 16192 twice, however this should only be counted once. The total count for ID 163 is 425.
