### ISSUE TITLE
7Span: Use of Manuscript Status for all Index and Detail pages (last check: map)

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#633]
WLB: Check map when back online

Note: We have edited this ticket to include simpler instructions below (12/18): 

## Manuscript Status
Note: Some manuscripts in the database should NOT appear anywhere on the website (not on the story detail page, not on the painting pages, not on the manuscript index page, not on the manuscript detail page).

### Manuscript Index and Manuscript detail pages
- [x] Do NOT display manuscripts with Manuscript table ms_status contains "Exclude"
Some examples: 
Exclude: collection
Exclude: duplicate
Exclude: irrelevant
Exclude: uncatalogable
Exclude: catalog
Exclude

### Story Index and Story Detail page **no action needed**
All excluded manuscripts have no stories in story instance sheet, so it is irrelevant

### Paintings Index and Detail pages **no action needed**
We have 9 excluded manuscripts with 11 cataloged paintings.
Right now, none of them are showing on the website. 
For instance, when I did a search for "crucifixion" in All Paintings no EMDL paintings showed up. 
No EMDL show up in Paintings by Manuscripts. 
No EMDL show up in Paintings by Story
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/78a97f9b-10fd-4c93-8a52-2a870136af80)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/bd1cb8b6-0b86-41cc-915a-ed80a562ee54)

**Comment by WendyLBelcher** [comment]
Complete = 674
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/ae26d3b5-c432-4a98-a8e2-806978d9ff1a)

EMDL to change to `Incomplete: Exclude collection's manuscripts`
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/8aeebd6f-8f52-41c4-8f44-4c0e73da5b41)

**Comment by blainealem** [comment]
### Notes
Incomplete: awaiting digitization (mostly HMML, this status may not longer be true, dated to spring 23)
Assigned to .... not included above, because will change quickly

**0 in category or now deleted**
Incomplete: being cataloged
Incomplete: almost done 
Incomplete: has print catalog
Unknown

### Example
For instance, this Manuscript Detail page should not exist:
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/6d9f59cb-fd48-4468-9f90-340973cb0e5e)

**Comment by blainealem** [comment]
### All Paintings Index Page

- [ ] Do not display manuscripts where `ms_status` contains "Exclude

- [ ] Remove "Ethiopian Manuscript Digital Library" from `Repository of Painting` dropdown 
<img width="1394" alt="Screen Shot 2023-12-18 at 7 44 03 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/8be5b7f2-36f2-4869-9a57-0ea7017a29cb">

**Comment by blainealem** [comment]
### Paintings by Story Index Page 

- [ ]  Do not display paintings from manuscripts where ms_status contains "Exclude"
- [ ] Update `Total paintings` to exclude manuscripts where ms_status contains "Exclude"

Question: Where is the the total paintings number generated from? Is it from the `Total_Story_ID_Paintings` field in `canonical story` directus table?
<img width="1397" alt="Screen Shot 2023-12-18 at 7 47 23 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/199a6549-eb4c-4c17-9e3d-2a1e380c2d56">

**Comment by blainealem** [comment]
### Paintings by Story Detail Page 

- [ ] Do not display paintings from manuscripts where ms_status contains "Exclude"
- [ ] 
<img width="1392" alt="Screen Shot 2023-12-18 at 7 50 31 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/d0ba180c-dfbd-44d0-9fe6-e63b0eeae6db">

**Comment by blainealem** [comment]
### Paintings by Manuscript Index Page
- [ ] Do not display paintings from manuscripts where `ms_status` contains "Exclude" (Question: Is this something that can be managed by PEMM team - for example, if we do not select a featured manuscript image for the manuscript, it will not appear on this page)
- [ ] Remove "Ethiopian Manuscript Digital Library" from `Repository of Painting` dropdown 

<img width="1383" alt="Screen Shot 2023-12-18 at 7 51 02 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/a7b28007-7aaf-4c8f-912a-fba993931445">

**Comment by blainealem** [comment]
### Incipit Tool 
- [ ] Do not display incipits from manuscripts where `ms_status` contains "Exclude"

**Comment by blainealem** [comment]
### Notes
Incomplete: awaiting digitization (mostly HMML, this status may not longer be true, dated to spring 23)
Assigned to .... not included above, because will change quickly

**0 in category or now deleted**
Incomplete: being cataloged
Incomplete: almost done 
Incomplete: has print catalog
Unknown

### Example
For instance, this Manuscript Detail page should not exist:
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/6d9f59cb-fd48-4468-9f90-340973cb0e5e)
