### ISSUE TITLE
7Span: Maps Bugs (12/17)

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#649]
- [ ] If `Manuscript `table `latitude `is null, do not display

- [ ] If `Manuscript `table `ms_status `contains "Exclude" do NOT display

Some examples:
Exclude: collection
Exclude: duplicate
Exclude: irrelevant
Exclude: uncatalogable
Exclude: catalog
Exclude

- [x] Make blue circle for 1 result more visible (make larger? make orange?)
Note: Even I keep not noticing it, a user will never realize it is a result
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/7ee001ec-ae30-47f5-a888-8fb03b1f87d2)

**Comment by blainealem** [comment]
**Update Maps filter header**

- [ ] "Paintings in Manuscript" header appears twice. Update the second one to read "Repository of Manuscript 
<img width="1400" alt="Screen Shot 2023-12-13 at 12 30 51 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/25f68201-ec77-4a61-86a3-8a7660dd7ed1">

**Comment by blainealem** [comment]
- [ ] Capitalize "ID" in the detail selection of manuscript

![image (15)](https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/e145e75c-2934-422b-826d-54e23b183ae9)

**Comment by blainealem** [comment]
- [ ] Include a zoom in and out feature similar to the one displayed[ here ](https://docs.mapbox.com/mapbox-gl-js/example/navigation/)

**Comment by blainealem** [comment]
- [ ] For singular location markers with mulltiple manuscripts, implement the [spiderify effect](https://github.com/bewithjonam/mapboxgl-spiderifier/blob/master/README.md)

**Comment by WendyLBelcher** [comment]
### Jeremy to look at
results (should be 2, not 11)

In Directus, UCLA does not have 11 manuscripts, it has 2
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/ca76f454-0edb-441b-a012-fb27e5f1b9ff)

In Directus, latitude between 34 and 35 has 12


But on the map, it shows it as having 11
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d607b9eb-2aed-40ac-918e-f40660320d5e)

**Comment by WendyLBelcher** [comment]
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/f86d40e9-a033-4917-a8eb-f8035fa2af53)

**Comment by WendyLBelcher** [comment]
### Ignore
results (should be 2, not 11)

In Directus, UCLA has 2 manuscripts, but EMIP has 9 manuscripts for UCLA
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/ca76f454-0edb-441b-a012-fb27e5f1b9ff)

In Directus, latitude between 34 and 35 has 12 (including Claremont)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d607b9eb-2aed-40ac-918e-f40660320d5e)

**Comment by WendyLBelcher** [comment]
### 7Span says the following is NOT possible:
For singular location markers with mulltiple manuscripts, implement the [spiderify effect](https://github.com/bewithjonam/mapboxgl-spiderifier/blob/master/README.md)

**Comment by blainealem** [comment]
<img width="1383" alt="Screen Shot 2023-12-18 at 8 00 54 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/e8f853c9-b1e2-426c-9694-c522980e1ad8">
