### ISSUE TITLE
7Span: Mobile View: Story Index Back Button (Henok must check)

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#651]
- [ ] Fix mobile breadcrumb issue

**Issue:** Users are receiving below error on mobile.

From the `story index` page, user clicks into a `story detail` page 
User then click the back button to go back to the `story index` page and receives the below error: 

![IMG_2187](https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/14c85e0c-fa33-4fd3-a9d9-3dedf3272374)

**Comment by henokalem** [comment]
The error happens on Chrome browser on IOS. And you have to repeat the process a few times before the error happens. That is go to index page, click into a story detail, go back to the index and click into a story detail. Doing this in succession several times is how I was able to reproduce it.

**Comment by henokalem** [comment]
I think it also helps if you change the page in the pagination. I usually have to do it several times to reproduce it.
