### ISSUE TITLE
7Span: Metadata and Google Search (wording changes only 1/10)

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#666]
### MetaDescription wording changes
For https://pemm.princeton.edu/paintings it should be
meta name="description" content="We provide beautiful African paintings of the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 1200s to the present; that is, medieval African paintings of Saint Mary; early modern African paintings of Saint Mary; and modern African paintings of Saint Mary."

For https://pemm.princeton.edu/about/connect/contact-us
Replace metadescription with
meta name="description" content="Contact PEMM with feedback and suggestions, or media inquiries, or info about how you used the site to extend your research or teaching, or requests for events, or ways to help or donate to the PEMM site about African stories, paintings, and manuscripts about the Virgin Mary created in Ethiopia, Eritrea, and Egypt in the 1200s to the present."

**Comment by WendyLBelcher** [comment]
Google results are not wrong (currently they are mostly wrong)?
- [ ] Correct `Princeton University` to say `Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary Project` 
- [ ] Correct `PEMM` to say  `Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary Project` for the home page

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/5744c031-52ac-48ef-8b41-3302bed28b4b)

- [ ] Correct  `Stories - PEMM - Princeton University `to be ` PEMM Stories`

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/31c28a65-28cf-46f4-bafa-90b1cdd00846)

- [ ] Correct  `Paintings- PEMM - Princeton University `to be ` PEMM Paintings`
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/51b7ad14-5c6d-47e5-b475-767c9112ef71)

**Comment by keval-7span** [comment]
Below is the page-wise meta description. Please update those accordingly.
https://pemm.princeton.edu
```
We provide beautifully illuminated African manuscripts and captivating stories about the Virgin Mary created in Ethiopia, Eritrea, and Egypt in the 1200s to the present.
```
https://pemm.princeton.edu/stories
```
We provide translations of captivating African stories in African languages about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 200s to the present.
```
https://pemm.princeton.edu/paintings
```
We provide beautifully illuminated African manuscripts with stories about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 1200s to the present.
```
https://pemm.princeton.edu/manuscripts
```
We provide information about African manuscripts with stories about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the late 1300s into the 1950s.
```
https://pemm.princeton.edu/research/maps
```
We map where African manuscripts with stories about the Virgin Mary are today and where they were created in Ethiopia, Eritrea, and Egypt from the late 1300s into the 1950s.
```
https://pemm.princeton.edu/research/incipit-tool
```
We provide a tool for identifying the titles of stories about the Virgin Mary preserved in Ethiopic in Ethiopia, Eritrea, and Egypt  from the 200s to the present.
```
https://pemm.princeton.edu/about/mission
```
The PEMM mission is to provide access to beautifully illuminated manuscripts and captivating stories about the Virgin Mary composed in African languages in Ethiopia, Eritrea, and Egypt from the 200s to the present.
```
https://pemm.princeton.edu/about/people
```
The PEMM team includes Ethiopians, Americans, and Ethiopian-Americans working to provide access to  paintings, stories, and manuscripts about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 200s to the present.
```
https://pemm.princeton.edu/about/news-and-updates
```
News about PEMM accomplishments in providing access to paintings, stories, and manuscripts about the Virgin Mary in Ethiopia, Eritrea, and Egypt from the 200s to the present.
```
https://pemm.princeton.edu/about/events-and-workshops
```
PEMM Events providing access to paintings, stories, and manuscripts about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 200s to the present.
```
https://pemm.princeton.edu/about/using-the-site
```
Get help in using the PEMM website and accessing paintings, stories, and manuscripts about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 200s to the present.
```
https://pemm.princeton.edu/research/research-and-lessons
```
PEMM conducts research and posts its findings about paintings, stories, and manuscripts about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 200s to the present.
```
https://pemm.princeton.edu/research/repositories
```
A list of the 92 repositories who have shared digital copies of their manuscripts about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 1200s to the present.
```
https://pemm.princeton.edu/research/macomber
```
PEMM takes advantage of a handlist created by William F. Macomber about around 640 manuscripts about the Virgin Mary created in Ethiopia.
```
https://pemm.princeton.edu/research/spellings
```
A list of the different spellings of proper nouns in the various languages used in the PEMM project
```
https://pemm.princeton.edu/research/bibliography
```
A list of bibliographic sources, articles and books, about the paintings, stories, and manuscripts about the Virgin Mary created in Ethiopia, Eritrea, and Egypt from the 200s to the present.
```
https://pemm.princeton.edu/research/arabic-manuscripts
```
A list of manuscripts in the Arabic language with stories about the Virgin Mary created between 1200 and 1900.
```
https://pemm.princeton.edu/research/arabic-stories
```
A list of stories that appear only in the Arabic language manuscripts about the Virgin Mary created outside of the Horn of Africa between 1200 and 1900.
```

**Comment by WendyLBelcher** [comment]
Google results are not wrong (currently they are mostly wrong)?
- [ ] Correct `Princeton University` to say `Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary Project` 
- [ ] Correct `PEMM` to say  `Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary Project` for the home page

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/5744c031-52ac-48ef-8b41-3302bed28b4b)

- [ ] Correct  `Stories - PEMM - Princeton University `to be ` PEMM Stories`

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/31c28a65-28cf-46f4-bafa-90b1cdd00846)

- [ ] Correct  `Paintings- PEMM - Princeton University `to be ` PEMM Paintings`
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/51b7ad14-5c6d-47e5-b475-767c9112ef71)

**Comment by WendyLBelcher** [comment]
### Ignore, Old
Google results are not wrong (currently they are mostly wrong)?
- [ ] Correct `Princeton University` to say `Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary Project` 
- [ ] Correct `PEMM` to say  `Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary Project` for the home page

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/5744c031-52ac-48ef-8b41-3302bed28b4b)

- [ ] Correct  `Stories - PEMM - Princeton University `to be ` PEMM Stories`

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/31c28a65-28cf-46f4-bafa-90b1cdd00846)

- [ ] Correct  `Paintings- PEMM - Princeton University `to be ` PEMM Paintings`
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/51b7ad14-5c6d-47e5-b475-767c9112ef71)

**Comment by WendyLBelcher** [comment]
### Ignore, Old
Google results are not wrong (currently they are mostly wrong)?
- [ ] Correct `Princeton University` to say `Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary Project` 
- [ ] Correct `PEMM` to say  `Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary Project` for the home page

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/5744c031-52ac-48ef-8b41-3302bed28b4b)

- [ ] Correct  `Stories - PEMM - Princeton University `to be ` PEMM Stories`

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/31c28a65-28cf-46f4-bafa-90b1cdd00846)

- [ ] Correct  `Paintings- PEMM - Princeton University `to be ` PEMM Paintings`
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/51b7ad14-5c6d-47e5-b475-767c9112ef71)

**Comment by WendyLBelcher** [comment]
Image sometimes, sometimes not
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/7694a203-084f-4c28-b041-e013d2045236)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/551727b1-0c6c-4e18-9fd6-f567a71c52b6)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/824b763e-094c-4d6a-98da-5cf42b72ea5a)

**Comment by hemratna** [comment]
@WendyLBelcher  
There is no direct way to show the image on Google search results.
This is happening based on Google's algorithm. 

At our end, we are not able to see the image for "PEMM Eritrea" as well as "PEMM Egypt"
https://prnt.sc/6BSsfBo7YDcX
https://prnt.sc/t6FK_Pwz8fFE

We will add some more meta data and hopefully Google will show the image. 

@keval-7span 

Let's create a schema for home page and add on website. 
https://technicalseo.com/tools/schema-markup-generator/

**Comment by WendyLBelcher** [comment]
@hemratna Yes, I understand. Probably, over time, it will start showing some of those images. So, I understand.
