### ISSUE TITLE
7Span: EthiopicMary redirect (Hem to advise)

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#694]
- [ ] Redirect from EthiopicMary.com to pemm.princeton.edu

Ethiopicmary.com shows up high in Google results
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/b9ddc535-3403-459b-b601-073cff45b861)
But link doesn't work
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/fd3ec4b8-9758-41f3-9dbe-75b4c7601ed0)

The reason ethiopicmary.com is showing the new site is because I added it as an additional domain in our amplify deployment. I figured it is better to show something than for it to just go to a dead page. The ideal state is when users go to ethiopicmary.com it will redirect to pemm.princeton.edu and users will see the new site, but it will be under the pemm.princeton.edu domain. The purpose of this ticket is to implement the redirect and delete the ethiopicmary.com domain I added to amplify as an additional domain. This image shows what it looks like in amplify: <img width="1163" alt="image" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/17439057/ede82505-5810-4bcf-9751-f4892b0e3ea9">

The ethiopicmary.com domain itself can be found in Route 53 of amplify, I believe that is where the redirect would need to be setup.

- [ ] Redirect from ethiopicmary.com to pemm.princeton.edu
The reason ethiopicmary.com is showing the new site is because I added it as an additional domain in our amplify deployment. I figured it is better to show something than for it to just go to a dead page. The ideal state is when users go to ethiopicmary.com it will redirect to pemm.princeton.edu and users will see the new site, but it will be under the pemm.princeton.edu domain. The purpose of this ticket is to implement the redirect and delete the ethiopicmary.com domain I added to amplify as an additional domain. This image shows what it looks like in amplify: [image.png (view on web)](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPrincetonPEMM%2F7Span-Phase2%2Fassets%2F17439057%2Fede82505-5810-4bcf-9751-f4892b0e3ea9&data=05%7C02%7Cwbelcher%40princeton.edu%7Ca8d950f09bde4d5a00da08dc0ba9b343%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638398070715928995%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dNYHusMfkJzPSnX7iGaw6vNAPDPayeUIz38jh5p93bc%3D&reserved=0)

**Comment by WendyLBelcher** [comment]
Redirect issue? I think this URL is an EthiopicMary.com issue
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/a73c062d-22ce-42b1-8f7d-e6452fe36ee2)

**Comment by WendyLBelcher** [comment]
Google search for PEMM stories 1/2/2024

Although it says PEMM Stories, it goes to 
https://pemm.princeton.edu/stories/182
https://pemm.princeton.edu/stories/111
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/bd75cb39-3c52-4419-9bee-474bf51f9064)

**Comment by henokalem** [comment]
The reason ethiopicmary.com is showing the new site is because I added it as an additional domain in our amplify deployment. I figured it is better to show something than for it to just go to a dead page. The ideal state is when users go to ethiopicmary.com it will redirect to pemm.princeton.edu and users will see the new site, but it will be under the pemm.princeton.edu domain. The purpose of this ticket is to implement the redirect and delete the ethiopicmary.com domain I added to amplify as an additional domain. This image shows what it looks like in amplify: <img width="1163" alt="image" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/17439057/ede82505-5810-4bcf-9751-f4892b0e3ea9">

**Comment by blainealem** [comment]
**Issue:** 

Google Search Result shows ethiopicmary.com/about page however there is no pemm.princeton.edu/about page so the link shows "Page Not Found" Error: 

**Google Search Results**
<img width="1432" alt="Screen Shot 2024-01-08 at 12 33 15 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/c2f59b45-8708-440d-90b2-9ccdea553c71">

**Page Not Found Error**
<img width="1425" alt="Screen Shot 2024-01-08 at 1 21 20 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/855ab4e1-9806-4242-8d73-24def287c2b7">

Fix: 

- [ ] Updated the ethiopicmary.com/about page to go to https://pemm.princeton.edu/about/mission#our-mission page
