### ISSUE TITLE
7Span: Incipit Tool test results

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#722]
## Test 1: With a Common Incipit (98 records)
Using incipit from EMML 8828, Story ID 1-A, s. 146b
በእንተ፡ ዘከመ፡ አስተርአየቶ፡ እግዝእትነ፡ ለቴዎፍሎስ፡ ሊቀ፡ ጳጳሳት ። ወዘከመ፡ ተናገረቶ፡ ወአጽንዓቶ፡ እምድካመ፡ ፍኖት ። ይቤ፡ ቴዎፍሎስ፡ ሊቀ፡ ጳጳሳት፡ ስምዑ፡ አበውየ፡ ወአኃውየ፡ ዘእነግረክሙ፡ በፍርሃት፡ ወበሃይማኖት፡ ርትዕት፡ ዘአስተርአየተኒ፡ እግዝ እትነ፡ ...
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/79226324-9510-4a3c-9518-9c8ef2517357)

### Pasted into Search with filter `Match Canonical Incipits Only`
Programming working: Retrieves 1-A as the first result, next results of 1-C and 2 and 3 also make sense, good
Errors: But exact matches not highlighted (is the problem the programming of the results or the programming of the highlighting?)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/2aec4e47-7281-44c4-af09-9d79e90f5470)

### Pasted into Search with filter `Match All Incipits`
Programming working: All exact matches are highlighted (change programming above to match this?); also retrieves many 1-A as the highest results, which is correct
Errors: Scan field not displayed; see ticket #723 
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/5b7e69b0-475c-45ea-a2f1-bc4469577beb)

**Comment by WendyLBelcher** [comment]
Test 2:
Using one word spelled two different ways: ምስጢረ with ስ and ምሥጢረ with ሥ 

Pasted into Search with filter Match All Incipits
Errors: Did not display incipits with ምስጢረ OR ምሥጢረ 
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/9341978d-5d66-4d9c-b9ea-22e38dde827b)

**Comment by WendyLBelcher** [comment]
Test 3
Incipit from EMML 22, ID 642, s. 150v (only 6 total records, only three incipits)
ወእምድኅረዝ፡ አስተርአዮ፡ መልአከ፡ እግዚአብሔር፡ ለዮሴፍ፡ በግብጽ፡ ወይቤሎ፡ ተንሥእ፡ ወንሣእ፡ ሕፃነ፡ ወእሞ፡ ወተመየጥ፡ ምድረ፡ ፍልስጥኤም

**Comment by blainealem** [comment]
### Test 4:
Using one word spelled two different ways: መጻሕፍት with ሕ and መጻህፍት with ህ 
<img width="213" alt="Screen Shot 2024-01-11 at 2 03 54 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/f1c86d36-6158-4780-bc8f-a41239815e3a">

In Directus, መጻ`ሕ`ፍት has 115 results in all incipits; መጻ`ህ`ፍት has 1 results in all incipits; so results should be at least 115 incipits have these words in them
<img width="1437" alt="Screen Shot 2024-01-11 at 2 07 06 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/6a0b0989-9f73-46ad-94c2-3e2104908d71">
<img width="1380" alt="Screen Shot 2024-01-11 at 2 06 35 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/a4204538-a881-46a7-bab8-b36293d52bc6">


In Directus, መጻ`ሕ`ፍት has 8 results in canonical incipits only; መጻ`ህ`ፍት has 0 results in canonical incipits only
<img width="1436" alt="Screen Shot 2024-01-11 at 2 08 56 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/c40bcbbc-09c2-404c-8909-764e912302c1">
<img width="1430" alt="Screen Shot 2024-01-11 at 2 09 43 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/2e5196d5-5bb5-4dc3-b5d3-714b523172f2">


Pasted መጻሕፍት into Search with filter `Match All Incipits` 
Programming did NOT work: Not all results are displayed, result should be at least 115
Programming did NOT work: No incipits with መጻህፍት are displayed; the results displays only incipits with መጻሕፍት
<img width="1423" alt="Screen Shot 2024-01-11 at 2 18 26 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/0754ba86-66f8-4afd-b69f-212a8d23fcf4">

Pasted መጻህፍት  into Search with filter `Match All Incipits`
Programming did NOT work: Not all results are displayed, result should be at least 115
Programming did NOT work: No incipits with መጻሕፍት are displayed; the results displays only incipits with መጻህፍት
<img width="1430" alt="Screen Shot 2024-01-11 at 2 19 21 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/c45461cb-7f94-41fd-934c-95f36e2c65d7">


Pasted መጻሕፍት into Search with filter `Match All Incipits` and then pasted መጻህፍት
Programming did NOT work: Not all results are displayed, result should be at least 115
Programming did NOT work: No incipits with መጻህፍት are displayed; the results displays only incipits with መጻሕፍት
<img width="1423" alt="Screen Shot 2024-01-11 at 2 18 26 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/0754ba86-66f8-4afd-b69f-212a8d23fcf4">

Pasted ምስጢረ into Search with filter `Match Canonical Incipits Only` and then pasted ምሥጢረ 
Programming does NOT work: Did not display all 7 incipits with either  ምስጢረ OR ምሥጢረ 
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/a54f0a7b-c478-4880-94f4-3a5692672a82)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/f63e3236-af72-41e7-bbca-dd122b872d3e)

**Comment by WendyLBelcher** [comment]
ብፅዕት does not give results for ብጽዕት

**Comment by WendyLBelcher** [comment]
ቀምር and ቅምር

**Comment by WendyLBelcher** [comment]
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/da3909a3-43fc-46c5-8ff0-c9c194be1375)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/1f630053-85a2-40a3-8b15-1a3dda219b05)
