### ISSUE TITLE
7Span: Paintings 5: Paintings by Manuscript Index Page

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#78]
### Purpose
Enables users to see the manuscripts with paintings. Only manuscripts with paintings will be displayed on this page (~240).

### Access
Accessed by clicking on navigation bar "Paintings" dropdown "Paintings by Manuscript" 

### Web Address
- [x] The web address for the `Paintings by Manuscript` Index Page is /paintings/by-manuscript
- [x] The link on all tiles on the `Paintings by Manuscript` Index Page is  /paintings/by-manuscript/ + `Manuscript `table `web_page_address`
For example, /paintings/by-manuscript/Gayant

### Design
- [x] Display one tile per manuscript with paintings (so about ~240 tiles)
- [x] Order tiles alphabetically by `Manuscript` table `manuscript`
- [ ] Include search bar, but NOT filter

### Programming
- [x] Display only those manuscripts where  `Manuscript` table `total_manuscript_paintings` > 0

Display on tile the painting marked `Manuscript` table `featured_manuscript_image_link` 

Wording below the painting:
- [x] Display `Manuscript` table `manuscript_full_name` field in regular font
- [x] Display `Manuscript `table `date_range_start` - `date_range_end` in smaller font
- [x] Display  `Manuscript `table `total_manuscript_paintings` in smaller font
- [x] If `Manuscript `table `scans_of_manuscript_in_color` field = `Yes`, display "in color" in smaller font
- [x] If `Manuscript `table `scans_of_manuscript_in_color` field = `No`, display "in black & white" in smaller font

For example:
**Ethiopian Manuscript Imaging Project, HMML Project ID EMIP, Manuscript No. 1039**
1450-1549
18 paintings in black & white

Create a button that says "View all images for this manuscript"

Note: Clicking on this button takes you to the Painting by Manuscript Detail Page

### Design
This screenshot only gives a general sense of the design: tiles with writing on black below

<img width="894" alt="Screen Shot 2023-08-22 at 3 00 53 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/fc09cb54-98ee-4314-818a-3cb280265ff6">

[ref design in dropbox](https://www.dropbox.com/scl/fi/i5odfi0wehyi74ea5ssa6/Paintings-by-manuscript-indez-page.png?rlkey=qsnc2jv83ihuos4lu4dpjyv1r&dl=0)

**Comment by blainealem** [comment]
The design of this page is the following: 

Tiles that feature a painting from a specific manuscript. @WendyLBelcher to add comments on which photo should be featured for a manuscript. 

- [ ] There will be a black box underneath the paintings that will show the manuscript name in bold. 
- [ ] Underneath it, in smaller font there will be a the century of the manuscript (century numeric, written in "00s" format)

<img width="894" alt="Screen Shot 2023-08-22 at 3 00 53 PM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/287a71de-79cc-4c41-bf91-fdce876dc293">


Manuscript name
tiles with paintings from this manuscript, each tile has a black box with the title of a story and folio and episodes description

**Comment by WendyLBelcher** [comment]
Design: 

- [ ] The top of the page will have the `manuscript_full_name` field in bold 
- [ ] Tiles underneath will show each painting in that manuscript

Underneath the paintings will be a black box that displays: 
- [ ]  `pemm_short_title` in bold (use the paintings table to identify `canonical_story_ID`, from there use the canonical story table to find the `pemm_short_title` 
- [ ] painting folio (@WendyLBelcher  to confirm)
- [ ] episodes (@WendyLBelcher  to confirm)

[reference design in dropbox link](https://www.dropbox.com/scl/fi/x8we95eqja5wajyhu2jxu/8A-Paintings-by-Manuscript-detail-page-rev2.pdf?rlkey=cechgzxj5ra0ij14yi930ww49&dl=0)

This page is designed to show all the paintings in one manuscript. To see its parent page, refer to #78. 

- [ ] This page can be access through 1) the navigation bar "Paintings by Manuscript" and then clicking on a tile or  (this page)

- [ ] or 2) through the Manuscript Detail page. To see all the paintings from a manuscript, one would click on the hyperlink in the manuscript description telling the number of paintings.
