### ISSUE TITLE
7Span: Manuscript, Stories, and Paintings Index Pages: CSV Export Function: Add fields to download (8 hours)

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#788]
###  Story Index page download, add fields to CSV (as last two columns, in the order below)
- [x] Display `Translation `table display `translation_status` if `translation_canonical_recension` = true
- [x] Display `Canonical story` table `origin` field 

###  Manuscript Index page download, add fields to CSV (as last eightcolumns, in the order below)
- [x] Display `Manuscript` table `manuscript_status` field
- [x] Display `Manuscript` table `total_folios` and `total_scans` fields
- [x] Display `Manuscript` table `royal_manuscript`
- [x] Display `Manuscript` table `location_of_ms_imaging_city` and `location_of_ms_imaging_country` and `ms_location_note`
- [x] Display `Manuscript` table `hamburg_link`

###  Paintings Index page download, add fields to CSV  (as last seven columns, in the order below)
- [x] Display `Paintings` table `total_manuscripts_with_this_story_illustrated`
- [x] Display `Paintings` table `total_manuscript_paintings`
- [x] Display `Manuscript` table `location_of_ms_imaging_city` and `location_of_ms_imaging_country` and `ms_location_note`
- [x] Display `Paintings` table `manuscript_link`
- [x] Display `Paintings` table `episode_keywords_objects`
- [x] Display `Paintings` table `episode_keywords_agents`

**Comment by blainealem** [comment]
Some examples: 

**Export icon**
<img width="995" alt="Screen Shot 2024-02-26 at 9 39 03 AM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/8f3c3b44-5720-4588-abc9-1b3e3e59a2f2">


**Export text**

<img width="1440" alt="Screen Shot 2024-02-26 at 9 43 16 AM" src="https://github.com/PrincetonPEMM/7Span-Phase2/assets/104459635/982eef77-8eb4-4b64-bb04-a15450fbf448">
