### ISSUE TITLE
7Span: Bug: Painting Index Page: Images not displaying

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/7Span-Phase2#972]
- [ ] Some images do not display on Paintings Index page (but do display on detail page)
Note: This may apply only to BOr 641 and 645?

Most images are loading fine
![image](https://github.com/user-attachments/assets/9273d884-9ad9-4811-abdf-bdf8561f14af)

But some images are not loading:
![image](https://github.com/user-attachments/assets/2d88b28e-c222-4b5a-903c-2ac5c1b1790b)

Even though we can see them in Directus
![image](https://github.com/user-attachments/assets/f042cd1d-5645-4cb0-889a-e1b68a75306f)

And we can see them in AWS
![image](https://github.com/user-attachments/assets/40c58ac3-1c17-4f86-9366-7f02f9398bfb)

This manuscript BOr 645, also has images in AWS that are not displaying
![image](https://github.com/user-attachments/assets/4df3ce9a-af88-4088-99d8-951ed1021956)

Here they are in AWS:
![image](https://github.com/user-attachments/assets/c5733746-6def-42e3-85b2-9f014b4e4657)

Maybe our naming convention is problematic.

**Comment by smtesfay772** [comment]
Hi Keval,

I uploaded more images and I'm running into the same issue. I tried opening another ticket but I can't seem to be able to assign it to you. Here's the link:

https://github.com/PrincetonPEMM/7Span-Phase2/issues/973
